# Generated by Django 2.0 on 2017-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Saldo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='ID da Conta')),
                ('action', models.CharField(max_length=150, verbose_name='Ação')),
                ('affected_account_id', models.IntegerField(verbose_name='ID da Conta Afetada')),
            ],
        ),
    ]
