# Generated by Django 2.0 on 2017-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='made_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Feito em...'),
        ),
    ]
