# Generated by Django 2.0 on 2017-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171210_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.IntegerField(verbose_name='Qtd. de Cédulas de P$1')),
                ('note2', models.IntegerField(verbose_name='Qtd. de Cédulas de P$2')),
                ('note5', models.IntegerField(verbose_name='Qtd. de Cédulas de P$5')),
                ('note10', models.IntegerField(verbose_name='Qtd. de Cédulas de P$10')),
                ('note20', models.IntegerField(verbose_name='Qtd. de Cédulas de P$20')),
                ('note50', models.IntegerField(verbose_name='Qtd. de Cédulas de P$50')),
                ('note100', models.IntegerField(verbose_name='Qtd. de Cédulas de P$100')),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
    ]
