# Generated by Django 2.0 on 2017-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171211_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='note1',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$1'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='note10',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$10'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='note100',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$100'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='note2',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$2'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='note20',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$20'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='note5',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$5'),
        ),
        migrations.AlterField(
            model_name='cashier',
            name='note50',
            field=models.IntegerField(default=10, verbose_name='Qtd. de Cédulas de P$50'),
        ),
    ]
